# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/movies-usf
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "dependencies.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      -  run:
          name: Run Unit Tests
          command: ./gradlew :app:testDebugUnitTest
      - save_cache:
          paths:
            - ~/.gradle
            - buildSrc
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "dependencies.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
